name: cocpit_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # ðŸŒ HTTP Requests
  http: ^1.1.0
  flutter_dotenv: ^5.1.0


  intl: ^0.19.0

  # ðŸ” Secure Storage for JWT
  flutter_secure_storage: ^9.0.0

  # ðŸ–¼ Media
  image_picker: ^1.1.2
  video_player: ^2.8.2

  # ðŸ˜Š Emoji picker
  emoji_picker_flutter: ^3.0.0

  # ðŸ”„ State management
  provider: ^6.0.5

  # ðŸŒ Explicit web dependency
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
    - .env
